// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package homebrew_computer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Introduction() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid grid-cols-2 sm:grid-cols-3\"><section class=\"col-span-2 w-full\"><h2 class=\"text-slate-300 italic font-bold text-left mx-10 my-5\">Welcome to to The Sullivan Code Blog!</h2><p class=\"text-slate-400 text-left mx-10 my-5\">I started this website to be a personal notepad, online resume, and guide to help others. I am passionate about learning and have made it my mission to share that knowledge. I hope that my works serve you as a useful and fun resource on your learning journey.</p><p class=\"hidden text-slate-400 text-left mx-10 my-5 sm:block\">-- Richard Sullivan</p></section><section class=\"mb-5 col-span-2 sm:col-span-1 flex flex-row justify-center w-full self-center sm:order-first\"><p class=\"text-slate-400 text-left mx-10 my-5 sm:hidden justify-self-center\">-- Richard Sullivan</p><img src=\"/media/portrait.png\" alt=\"self portrait of website author\" class=\"max-w-40\"></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
